// Generated by CoffeeScript 1.3.1
(function() {
  var $;

  $ = jQuery;

  $(function() {
    window.prettyPrint();
    return $('[rel=tooltip]').tooltip({
      placement: 'right'
    });
  });

}).call(this);
