// Generated by CoffeeScript 1.3.1
var listener;

self.importScripts('../../js/mylibs/mandelbrot-core.js');

listener = function(e) {
  var data, escapeTimes, mandelbrot, message,
    _this = this;
  mandelbrot = new self.MandelbrotCore(function(progress) {
    var message;
    message = JSON.stringify({
      message: "progress",
      value: progress
    });
    return _this.postMessage(message);
  });
  data = JSON.parse(e.data);
  escapeTimes = mandelbrot.getEscapeTimes(data.width, data.height, data.box, data.maxIterations);
  message = JSON.stringify({
    message: "success",
    value: escapeTimes
  });
  return this.postMessage(message);
};

this.addEventListener('message', listener, false);
