// Generated by CoffeeScript 1.3.1
(function() {
  var Mandelbrot;

  Mandelbrot = (function() {
    var drawMandelbrot, getEscapeTimeAtPixel, setCanvasSize;

    function Mandelbrot(canvasId) {
      this.canvasId = canvasId;
      $(function() {
        var canvas;
        canvas = document.getElementById(canvasId);
        if (canvas != null) {
          this._context = canvas.getContext('2d');
        }
        setCanvasSize(this._context);
        return drawMandelbrot(this._context);
      });
      window.resize(function() {
        return setCanvasSize(this._context);
      });
    }

    drawMandelbrot = function() {
      var column, escapeTimes, height, pixels, row, width, _i, _j;
      width = this._context.canvas.width;
      height = this._context.canvas.height;
      pixels = this._context.createImageData(width, height);
      escapeTimes = [];
      for (column = _i = 1; 1 <= width ? _i <= width : _i >= width; column = 1 <= width ? ++_i : --_i) {
        for (row = _j = 1; 1 <= height ? _j <= height : _j >= height; row = 1 <= height ? ++_j : --_j) {
          escapeTimes.push(getEscapeTimeAtPixel(row, column));
        }
      }
      this._context.fillStyle = 'red';
      this._context.fillRect(30, 30, 50, 50);
      return escapeTimes;
    };

    getEscapeTimeAtPixel = function(row, column) {
      return row + column;
    };

    setCanvasSize = function() {
      var width;
      width = $('#' + this.canvasId).parent().width();
      this._context.canvas.width = width;
      return this._context.canvas.height = width * 2 / 3.0;
    };

    return Mandelbrot;

  })();

}).call(this);
