// Generated by CoffeeScript 1.3.3

self.importScripts('../../js/libs/require.js');

self.require(["mandelbrot-core"], function(MandelbrotCore) {
  var listener;
  listener = function(e) {
    var data, escapeTimes, mandelbrot, message,
      _this = this;
    mandelbrot = new MandelbrotCore(function(progress) {
      var message;
      message = JSON.stringify({
        message: "progress",
        value: progress
      });
      return _this.postMessage(message);
    });
    if (e.data != null) {
      data = JSON.parse(e.data);
      escapeTimes = mandelbrot.getEscapeTimes(data.width, data.height, data.box, data.maxIterations);
      message = JSON.stringify({
        message: "success",
        value: escapeTimes
      });
      return this.postMessage(message);
    }
  };
  return this.addEventListener('message', listener, false);
});
